### Actualizar parcialmente puntaje y nivel de riesgo
PATCH http://localhost:4004/odata/v4/admin/Suppliers(11d53c05-06f5-41ff-85ef-3f6227686c8a)
Content-Type: application/json

{
  "riskScore": 72,
  "riskLevel": "MEDIUM"
}

### Bloquear proveedor y marcarlo como alto riesgo
PATCH http://localhost:4004/odata/v4/admin/Suppliers(11d53c05-06f5-41ff-85ef-3f6227686c8a)
Content-Type: application/json

{
  "status": "BLOCKED",
  "riskScore": 95,
  "riskLevel": "HIGH"
}
