### Expandir categoria de cada proveedor
GET http://localhost:4004/odata/v4/risk/Suppliers?$expand=category

### Expandir categoria mostrando solo campos principales del proveedor
GET http://localhost:4004/odata/v4/risk/Suppliers?$select=name,country,riskLevel&$expand=category($select=name)

### Expandir contactos de cada proveedor
GET http://localhost:4004/odata/v4/risk/Suppliers?$expand=contacts

### Expandir contactos mostrando solo campos principales
GET http://localhost:4004/odata/v4/risk/Suppliers?$select=name,country,riskLevel&$expand=contacts($select=firstName,lastName,role,email,isPrimary)

### Expandir categoria y contactos del proveedor
GET http://localhost:4004/odata/v4/risk/Suppliers?$select=name,country,riskLevel&$expand=category($select=name),contacts($select=firstName,lastName,role,isPrimary)
